export const ADMIN_ORDER_REQUEST = "ADMIN_ORDER_REQUEST";
export const ADMIN_ORDER_SUCCESS = "ADMIN_ORDER_SUCCESS";
export const ADMIN_ORDER_FAILURE = "ADMIN_ORDER_FAILURE";

export const ADMIN_USERS_REQUEST = "ADMIN_USERS_REQUEST";
export const ADMIN_USERS_SUCCESS = "ADMIN_USERS_SUCCESS";
export const ADMIN_USERS_FAILURE = "ADMIN_USERS_FAILURE";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAILURE = "ADMIN_PRODUCT_FAILURE";

export const ADMIN_ADD_PRODUCT_REQUEST = "ADMIN_ADD_PRODUCT_REQUEST";
export const ADMIN_ADD_PRODUCT_SUCCESS = "ADMIN_ADD_PRODUCT_SUCCESS";
export const ADMIN_ADD_PRODUCT_FAILURE = "ADMIN_ADD_PRODUCT_FAILURE";

export const RESET_ERROR = "RESET_ERROR";
