export const ADMIN_ORDER_REQUEST = "ADMIN_ORDER_REQUEST";
export const ADMIN_ORDER_SUCCESS = "ADMIN_ORDER_SUCCESS";
export const ADMIN_ORDER_FAILURE = "ADMIN_ORDER_FAILURE";
export const RESET_ERROR = "RESET_ERROR";
